version: '3'
services:
  agent:
    build:
      context: .
    volumes:
      - agentmodel:/model
    image: kulhanek/visual-navigation-agent-pytorch

  train:
    command: "python /app/train.py"
    image: kulhanek/visual-navigation-agent-pytorch

volumes:
  agentmodel: